use_frameworks!

platform :ios, '8.0'

target 'YDQSModuleSDK_Example' do
  pod 'YDQSModuleSDK', :path => '../'

  target 'YDQSModuleSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
  pod 'YDBaseClassSDK' ,:git =>"https://github.com/JamWangJam/YDBaseClassSDK.git"
  pod 'YDCategorySDK' ,:git =>"https://github.com/JamWangJam/YDCategorySDK.git"
end
